source 'https://rubygems.org'
ruby '2.7.0'
gem 'bootsnap'
gem 'eventmachine'
gem 'faye-websocket'
gem 'ginseng-core', git: 'https://github.com/pooza/ginseng-core.git'
gem 'ginseng-postgres', git: 'https://github.com/pooza/ginseng-postgres.git'
gem 'ginseng-web', git: 'https://github.com/pooza/ginseng-web.git'
gem 'natto'
gem 'rubicure', git: 'https://github.com/pooza/rubicure.git', branch: 'master.pooza'
gem 'rubocop'
gem 'rubocop-performance'
gem 'sanitize'
gem 'sidekiq', git: 'https://github.com/mperham/sidekiq.git'
gem 'sidekiq-scheduler'
gem 'timecop'
