source 'https://rubygems.org'
ruby '~>3.0.0'
gem 'bootsnap'
gem 'faye-websocket'
gem 'ginseng-core', github: 'pooza/ginseng-core'
gem 'ginseng-fediverse', github: 'pooza/ginseng-fediverse', require: 'ginseng/fediverse'
gem 'ginseng-postgres', github: 'pooza/ginseng-postgres', require: 'ginseng/postgres'
gem 'ginseng-web', github: 'pooza/ginseng-web', require: 'ginseng/web'
gem 'natto'
gem 'rubicure', github: 'pooza/rubicure', branch: 'master.pooza'
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'sidekiq-scheduler'

group :development do
  gem 'rack-test'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-sequel', github: 'pooza/rubocop-sequel', branch: 'master.pooza'
  gem 'test-unit'
  gem 'timecop'
end
