# NGワード設定ファイル
#
# @package jp.co.b-shock.carrot
# @author 小石達也 <tkoishi@b-shock.co.jp>

words:
  - あいえき
  - アイエキ
  - あいぶ
  - アイブ
  - アイフ゛
  - アイ液
  - あい液
  - あい撫
  - アイ撫
  - あおかん
  - アオカン
  - あくめ
  - アクメ
  - あすふぁっく
  - アスファック
  - あなる
  - アナル
  - あぬす
  - アヌス
  - あめこう
  - アメコウ
  - アメ公
  - イッちゃう
  - いめくら
  - イメクラ
  - いめくら嬢
  - イメクラ嬢
  - いんけい
  - インケイ
  - いんこう
  - インコウ
  - いんのう
  - インノウ
  - いんばい
  - インバイ
  - インハ゛イ
  - いんぶ
  - インブ インフ゛
  - インフ゛
  - インブ
  - いンぶ
  - イんぶ
  - インぶ
  - イんブ
  - いんブ
  - いんフ゛
  - いんぽ
  - インポ
  - インホ゜
  - いんもう
  - インモウ
  - いんらん
  - インラン
  - イン茎
  - いん茎
  - イン唇
  - いん唇
  - イン賑
  - いん賑
  - イン嚢
  - いん嚢
  - イン毛
  - いん毛
  - イン乱
  - いん乱
  - う゛ぁぎな
  - ヴァギナ
  - ウ゛ァキ゛ナ
  - ヴァキ゛ナ
  - ウ゛ァギナ
  - うまずめ
  - ウマズメ
  - ウマス゛メ
  - うんこ
  - ウンコ
  - うんち
  - ウンチ
  - えいず
  - エイズ
  - エイス゛
  - えすえむ
  - エスエム
  - オウゴン水
  - オウコ゛ン水
  - おうごん水
  - おーがずむ
  - オーガズム
  - オーカ゛ス゛ム
  - オーガス゛ム
  - オーカ゛ズム
  - おわいや
  - おかして
  - オカシテ
  - おかま
  - オカマ
  - おしっこ
  - オシッコ
  - おっぱい
  - オッパイ
  - オッハ゜イ
  - おなに
  - オナニ
  - おなにぃ
  - オナニィ
  - ナニィ
  - おなにー
  - オナニー
  - おなぺっと
  - オナペット
  - オナヘ゜ット
  - おなる
  - オナル
  - オナる
  - おまんこ
  - オマンコ
  - おまんコ
  - おめこ
  - オメコ
  - おるがずむ
  - オルガズム
  - オルカ゛ス゛ム
  - オワイヤ
  - オ満子
  - かたわ
  - カタワ
  - がんしゃ
  - ガンシャ
  - カ゛ンシャ
  - がん射
  - ガン射
  - カ゛ン射
  - きじるし
  - キジルシ
  - キシ゛ルシ
  - きちがい
  - キチガイ
  - キチカ゛イ
  - キッコウ縛り
  - ぎっちょ
  - ギッチョ
  - キ゛ッチョ
  - キッチョ
  - きょこん
  - キョコン
  - キョ根
  - きょ根
  - きんたま
  - キンタマ
  - くまんこ
  - クマンコ
  - くみとりや
  - クミトリヤ
  - クミトリ屋
  - くみとり屋
  - くりとりす
  - クリトリス
  - くろんぼ
  - クロンボ
  - クロンホ゛
  - クンニ
  - ケチャマン
  - こうがん
  - コウガン
  - コウカ゛ン
  - ごうかん
  - ゴウカン
  - コ゛ウカン
  - こうび
  - コウビ
  - コウヒ゛
  - コウマン
  - こうまん
  - こうもん
  - コウモン
  - ゴウ姦
  - コ゛ウ姦
  - ごう姦
  - こう丸
  - コウ丸
  - コウ門
  - こう門
  - こじき
  - コジキ
  - コシ゛キ
  - こーまん
  - コーマン
  - こんどうむ
  - コンドウム
  - コント゛ウム
  - ンドウム
  - こんどーむ
  - コンドーム
  - コント゛ーム
  - ざぁめん
  - ザァメン
  - サ゛ァメン
  - ざあめん
  - ザアメン
  - サ゛アメン
  - ざーめん
  - ザーメン
  - サ゛ーメン
  - さおのつゆ
  - サオのつゆ
  - サオノツユ
  - サオの液
  - さおの液
  - サオの汁
  - さおの汁
  - サオの露
  - さおの露
  - さでぃずむ
  - サディズム
  - サディス゛ム
  - サテ゛ィス゛ム
  - サテ゛ィズム
  - さんごくじん
  - サンゴクジン
  - サンゴクシ゛ン
  - サンコ゛クシ゛ン
  - サンコ゛クジン
  - じーすぽっと
  - ジースポット
  - ジースホ゜ット
  - シ゛ースポット
  - シ゛ースホ゜ット
  - しっこ
  - シッコ
  - しゃせい
  - シャセイ
  - じゃっぷ
  - ジャップ
  - シ゛ャッフ゜
  - ジャッフ゜
  - ャッフ゜
  - シ゛ャップ
  - じゃぱゆき
  - ジャパユキ
  - シ゛ャハ゜ユキ
  - ジャハ゜ユキ
  - シ゛ャパユキ
  - シャ精
  - しゃ精
  - しょうべん
  - ショウベン
  - ショウヘ゛ン
  - じょきゅう
  - ジョキュウ
  - シ゛ョキュウ
  - しょじょまく
  - ショジョマク
  - ショシ゛ョマク
  - じょちゅー
  - ジョチュー
  - シ゛ョチュー
  - じょちゅう
  - ジョチュウ
  - シ゛ョチュウ
  - しらこ
  - シラコ
  - しらっこ
  - シラッコ
  - しんしょう
  - シンショウ
  - しん障
  - シン障
  - すかとろ
  - スカトロ
  - すぺるま
  - スペルマ
  - スヘ゜ルマ
  - すまた
  - スマタ
  - ス股
  - す股
  - せいえき
  - セイエキ
  - せいき
  - セイキ
  - せいこうい
  - セイコウイ
  - セイ液
  - せい液
  - せい器
  - セイ器
  - セイ具
  - せい具
  - セイ行為
  - せい行為
  - せっくす
  - セックス
  - せっくる
  - セックル
  - せむし
  - セムシ
  - せんじん
  - センジン
  - センシ゛ン
  - せんずり
  - センズリ
  - センス゛リ
  - そうじふ
  - ソウジフ
  - ソウシ゛フ
  - そうぷじょう
  - ソウプジョウ
  - ソウフ゜シ゛ョウ
  - ソウプシ゛ョウ
  - ソウフ゜ジョウ
  - ソウプ嬢
  - そうぷ嬢
  - ソウフ゜嬢
  - そうろう
  - ソウロウ
  - ソウ漏
  - そう漏
  - そーぷじょう
  - ソープジョウ
  - ソーフ゜シ゛ョウ
  - ソープシ゛ョウ
  - ソーフ゜ジョウ
  - ソープ嬢
  - そーぷ嬢
  - ソーフ゜嬢
  - だいいんしん
  - ダイインシン
  - タ゛イインシン
  - ダイインシ゛ン
  - タ゛イイジンシン
  - だいべん
  - ダイベン
  - タ゛イヘ゛ン
  - ダイヘ゛ン
  - タ゛イベン
  - たいわんはげ
  - タイワンハゲ
  - タイワンハケ゛
  - ダイ陰唇
  - タ゛イ陰唇
  - だい陰唇
  - だっちまん
  - だっぷん
  - ダップン
  - タ゛ッフ゜ン
  - ダッフ゜ン
  - タ゛ップン
  - たまきん
  - タマキン
  - たまぶくろ
  - タマブクロ
  - タマフ゛クロ
  - タマ金
  - たま金
  - たんぽん
  - タンポン
  - タンホ゜ン
  - ちえおくれ
  - チエオクレ
  - ちえ遅れ
  - ちくび
  - チクビ
  - チクヒ゛
  - ちゃんころ
  - チャンコロ
  - ちょん
  - チョン
  - ちろう
  - チロウ
  - ちんげ
  - チンゲ
  - チンケ゛
  - ちんこ
  - チンコ
  - ちんちん
  - チンチン
  - ちんば
  - チンバ
  - チンハ゛
  - ちんぼ
  - チンボ
  - チンホ゛
  - ちんぽ
  - チンポ
  - チンホ゜
  - チン毛
  - ちん毛
  - ち骨
  - チ首
  - ち首
  - ち漏
  - つんぼ
  - ツンボ
  - ツンホ゛
  - ていもう
  - テイモウ
  - てい毛
  - テイ毛
  - てぃんぽ
  - ティンポ
  - ティンホ゜
  - てぃんこ
  - ティンコ
  - てぃむぽ
  - ティムポ
  - ティムホ゜
  - てぃんてぃん
  - ティンティン
  - ていのう
  - テイノウ
  - てい脳
  - テイ脳
  - でかまら
  - デカマラ
  - テ゛カマラ
  - てこき
  - テコキ
  - てまん
  - テマン
  - どかた
  - ドカタ
  - ト゛カタ
  - とさつ
  - トサツ
  - どじん
  - ドジン
  - ト゛シ゛ン
  - ドシ゛ン
  - ト゛ジン
  - ドモリ
  - ト゛モリ
  - とるこじょう
  - トルコジョウ
  - トルコシ゛ョウ
  - とるこぶろ
  - トルコブロ
  - トルコフ゛ロ
  - トルコ嬢
  - とるこ嬢
  - トルコ風呂
  - とるこ風呂
  - ト殺
  - と殺
  - なかだし
  - ナカダシ
  - ナカタ゛シ
  - なか出し
  - ナカ出し
  - なまだし
  - ナマダシ
  - ナマタ゛シ
  - なま出し
  - ナマ出し
  - にがあ
  - ニガア
  - ニカ゛ア
  - にがー
  - ニガー
  - ニカ゛ー
  - にぐろ
  - ニグロ
  - ニク゛ロ
  - にゅうりん
  - ニュウ輪
  - にゅう輪
  - ニンソク
  - のうたりん
  - ノウタリン
  - のうらん
  - ノウラン
  - ノウ乱
  - のう乱
  - のーたりん
  - ノータリン
  - ぱいおつ
  - パイオツ
  - ハ゜イオツ
  - ぱーるろーた
  - パールロータ
  - ハ゜ールロータ
  - ぱいずり
  - パイズリ
  - ハ゜イス゛リ
  - パイス゛リ
  - ハ゜イズリ
  - ばいぶ
  - バイブ
  - ハ゛イフ゛
  - バイフ゛
  - ハ゛イブ
  - ばかちょん
  - バカチョン
  - ハ゛カチョン
  - ばかちん
  - バカチン
  - ハ゛カチン
  - ばぎな
  - バギナ
  - ハ゛キ゛ナ
  - バキ゛ナ
  - ハ゛ギナ
  - ハクチ
  - はめどり
  - ハメドリ
  - ハメト゛リ
  - ハメ撮り
  - はめ撮リ
  - はめ撮り
  - びっこ
  - ビッコ
  - ヒ゛ッコ
  - びっち
  - ビッチ
  - ヒ゛ッチ
  - ひとりえっち
  - ヒトリエッチ
  - ひにん
  - ヒニン
  - びらびら
  - ビラビラ
  - ヒ゛ラヒ゛ラ
  - ビラヒ゛ラ
  - ヒ゛ラビラ
  - ぴんくろーた
  - ピンクロータ
  - ヒ゜ンクロータ
  - ふぁっかー
  - ファッカー
  - ふぁっきん
  - ファッキン
  - ふぁっく
  - ファック
  - ふぁっくあす
  - ファックアス
  - ふぁっくおふ
  - ファックオフ
  - ふぁっくど
  - ファックド
  - ファックト゛
  - ふぇら
  - フェラ
  - ふぇらちお
  - フェラチオ
  - ふぐり
  - フグリ
  - フク゛リ
  - ぷっしぃ
  - プッシィ
  - フ゜ッシィ
  - ぷっしー
  - プッシー
  - フ゜ッシー
  - ぶらく
  - ブラク
  - フ゛ラク
  - ぺってぃんぐ
  - ペッティング
  - ヘ゜ッティンク゛
  - ペッティンク゛
  - ヘ゜ッティング
  - ぺにす
  - ペニス
  - ヘ゜ニス
  - へるすじょう
  - ヘルスジョウ
  - ヘルスシ゛ョウ
  - へるす嬢
  - ヘルス嬢
  - ほうにょう
  - ホウニョウ
  - ホウ尿
  - ほう尿
  - ぽこちん
  - ポコチン
  - ホ゜コチン
  - ぼっき
  - ボッキ
  - ホ゛ッキ
  - ボッ起
  - ぼっ起
  - ホ゛ッ起
  - ほも
  - ホモ
  - マエツキ
  - マツエキ
  - まえ付き
  - マエ付き
  - まぐあい
  - マグアイ
  - マク゛アイ
  - ますをかく
  - マスヲカク
  - マスをかく
  - マスを掻く
  - ますを掻く
  - まぞひずむ
  - マゾヒズム
  - マソ゛ヒス゛ム
  - マゾヒス゛ム
  - マソ゛ヒズム
  - まんぐり
  - マングリ
  - マンク゛リ
  - まんげ
  - マンゲ
  - マンケ゛
  - まんこ
  - マンコ
  - マんこ
  - マんコ
  - マンこ
  - まンコ
  - まんコ
  - まンこ
  - ちんコ
  - うんコ
  - まんじる
  - マンジル
  - マンシ゛ル
  - まんちょ
  - マンチョ
  - マン汁
  - まん汁
  - マン毛
  - まん毛
  - みつくち
  - ミツクチ
  - めかけ
  - メカケ
  - めくら
  - メクラ
  - めんす
  - メンス
  - メ暗
  - め暗
  - もんもう
  - モンモウ
  - やらせろ
  - ヤラセロ
  - ヤらせろ
  - ヤラせろ
  - やりまん
  - ヤリマン
  - ゆびまん
  - ユビマン
  - ユヒ゛マン
  - よがらせて
  - ヨガラセテ
  - ヨカ゛ラセテ
  - よばい
  - ヨバイ
  - ヨハ゛イ
  - ヨ這
  - よ這
  - らいびょう
  - ライビョウ
  - ライヒ゛ョウ
  - ライ病
  - らい病
  - りょうじょく
  - リョウジョク
  - リョウシ゛ョク
  - れいぷ
  - レイプ
  - レイフ゜
  - レズ
  - レス゛
  - れずびあん
  - レズビアン
  - レス゛ヒ゛アン
  - レズヒ゛アン
  - レス゛ビアン
  - ろすけ
  - ロスケ
  - ろんぱり
  - ロンパリ
  - ロンハ゜リ
  - ワレメ
  - ワレ目
  - われ目
  - ワ姦
  - わ姦
  - 姦
  - 愛えき
  - 愛ぶ
  - 愛液
  - 愛撫
  - 淫コウ
  - 淫こう
  - 淫ラン
  - 淫らん
  - 淫行
  - 淫乱
  - 陰カク
  - 陰かく
  - 陰ケイ
  - 陰けい
  - 陰シン
  - 陰しん
  - 陰ノウ
  - 陰もう
  - 陰モウ
  - 陰核
  - 陰茎
  - 陰唇
  - 陰嚢
  - 陰毛
  - 陰部
  - 黄金水
  - 割レメ
  - 割れめ
  - 顔シャ
  - 割れ目
  - 割目
  - 顔しゃ
  - 顔射
  - 亀甲しばり
  - 亀甲縛り
  - 汲み取り屋
  - 巨コン
  - 巨こん
  - 巨根
  - 強かん
  - 強カン
  - 強姦
  - 狂ジルシ
  - 狂シ゛ルシ
  - 狂じるし
  - 狂印
  - 玉きん
  - 玉キン
  - 玉金
  - 玉ぶくろ
  - 玉ブクロ
  - 玉フ゛クロ
  - 玉袋
  - 金玉
  - 交尾
  - 黒んぼ
  - 黒ンボ
  - 黒ンホ゛
  - 三国人
  - 殺す
  - 殺ス
  - 殺せ
  - 殺セ
  - 産婆
  - 自慰
  - 死ね
  - 死ネ
  - 指マン
  - 指まん
  - 射セイ
  - 射せい
  - 処女
  - 処女膜
  - 女給
  - 女中
  - 妾
  - 小便
  - 人足
  - 身しょう
  - 身ショウ
  - 性コウイ
  - 身障
  - 性グ
  - 性ク゛
  - 性ぐ
  - 性こうい
  - 性器
  - 性具
  - 性行為
  - 生ダシ
  - 生タ゛シ
  - 生だし
  - 生出し
  - 精エキ
  - 精えき
  - 精液
  - 精道
  - 石女
  - 責め棒
  - 前ツキ
  - 前つき
  - 前付き
  - 素マタ
  - 素また
  - 素股
  - 掃除夫
  - 早ロウ
  - 早ろう
  - 早漏
  - 大陰唇
  - 大便
  - 脱ふん
  - 恥丘
  - 恥こつ
  - 恥骨
  - 痴ジル
  - 痴シ゛ル
  - 痴じる
  - 痴汁
  - 遅ろう
  - 遅漏
  - 中ダシ
  - 中タ゛シ
  - 中だし
  - 中出し
  - 恥部
  - 低ノウ
  - 低のう
  - 低脳
  - 剃モウ
  - 剃もう
  - 剃毛
  - 手こき
  - 手コキ
  - 手まん
  - 手マン
  - 屠さつ
  - 屠サツ
  - 屠殺
  - 土人
  - 土方
  - 童貞
  - 乳クビ
  - 乳クヒ゛
  - 乳くび
  - 乳リン
  - 乳りん
  - 乳首
  - 乳輪
  - 肉棒
  - にくぼう
  - 尿
  - 悩乱
  - 脳タリン
  - 脳たりん
  - 脳ラン
  - 脳らん
  - 脳足りん
  - 背虫
  - 白子
  - 白雉
  - 白痴
  - 犯シテ
  - 犯して
  - 部落
  - 文盲
  - 放ニョウ
  - 放にょう
  - 放尿
  - 勃起
  - 射精
  - 膣内射精
  - 口内射精
  - 肉芽
  - 援助交際
  - 援交
  - 青姦
  - 膣腔
  - 視姦
  - 性感
  - 無修正
  - 目クラ
  - 目くら
  - 目暗
  - 夜バイ
  - 夜ハ゛イ
  - 夜ばい
  - 夜這
  - 夜這い
  - 凌辱
  - 和カン
  - 和かん
  - 和姦
  - 揉んで
  - 殷シン
  - 殷しん
  - 殷賑
  - 睾ガン
  - 睾カ゛ン
  - 睾がん
  - 睾丸
  - 肛モン
  - 肛もん
  - 肛門
  - 膣
  - AIDS
  - ＡＩＤＳ
  - anal
  - ａｎａｌ
  - ass
  - ａｓｓ
  - bitch
  - ｂｉｔｃｈ
  - dick
  - ｄｉｃｋ
  - dutch
  - fuck
  - FUCK
  - ｆｕｃｋ
  - ＦＵＣＫ
  - FUCＫ
  - fuckyou
  - FUCKYOU
  - gay
  - ｇａｙ
  - hacking
  - hentai
  - ｈｅｎｔａｉ
  - jesus
  - kill
  - ｋｉｌｌ
  - lesbian
  - ｌｅｓｂｉａｎ
  - orgasm
  - ｏｒｇａｓｍ
  - porn
  - ｐｏｒｎ
  - pussy
  - ｐｕｓｓｙ
  - rape
  - ｒａｐｅ
  - ＳＥＸ
  - SEX
  - ｓｅｘ
  - sex
  - ＳEＸ
  - shit
  - ｓｈｉｔ
  - stupid
  - ｓｔｕｐｉｄ
  - 麻原彰晃
  - アーレフ
  - アレフ
  - オウム
  - 真理教
  - 幸福の科学
  - 佼成
  - 創価
  - 池田大作
  - 統一教会
  - 文鮮明
  - 金正日
  - 将軍様
  - 酒鬼薔薇
  - 2ch
  - ２ｃｈ
  - ２ちゃんねる
  - 2ちゃんねる
  - ２チャンネル
  - 2チャンネル
  - Ｇスポット
  - Ｇｽﾎﾟｯﾄ
  - Ｇスポッﾄ
  - Ｇスポｯﾄ
  - Ｇスﾎﾟｯﾄ
  - Ｇｽポット
  - Ｇｽﾎﾟット
  - Ｇｽﾎﾟｯト
  - MANKO
  - manko
  - あめ公
  - イラマチオ
  - イﾝポ
  - ウﾝチ
  - エッチ
  - えっち
  - エロ動画
  - ｵﾅニ
  - オナﾆー
  - オﾅニー
  - オﾅﾆー
  - オナﾍﾟｯト
  - カジノ
  - かたわ
  - ｶﾀワ
  - きっこう縛り
  - ｷｯｺｳ縛り
  - キャバクラ
  - キャバ嬢
  - ギャンブル
  - 黒ん
  - けちゃまん
  - ｺｳﾓﾝ
  - コウモﾝ
  - コウﾓﾝ
  - コｳﾓﾝ
  - ｺウモン
  - ｺｳモン
  - ｺｳﾓン
  - コンﾄﾞｰﾑ
  - ｺﾝドーム
  - ｻﾞｧﾒﾝ
  - サド
  - サラ金
  - 宗教
  - スワッピング
  - セフレ
  - ダイインシﾝ
  - ダイインｼﾝ
  - ダイイﾝｼﾝ
  - ダイｲﾝｼﾝ
  - ダｲｲﾝｼﾝ
  - ﾀﾞイインシン
  - ﾀﾞｲインシン
  - ﾀﾞｲｲンシン
  - ﾀﾞｲｲﾝシン
  - ﾀﾞｲｲﾝｼン
  - 崇教
  - 朝鮮
  - チョソ
  - チョンコー
  - チ骨
  - ﾁ骨
  - チ漏
  - ﾁ漏
  - ﾃィムポ
  - ﾃィンポ
  - ﾃイ脳
  - デリヘル
  - どもり
  - ﾅｶダシ
  - ナｶダシ
  - ﾅカダシ
  - ナンパ
  - ﾆガー
  - ニュウリン
  - にんそく
  - はくち
  - ﾊクチ
  - パチスロ
  - パチンコ
  - パンツ
  - パンティ
  - ﾋトリエッチ
  - ﾋﾄリエッチ
  - ﾋﾄﾘエッチ
  - ﾋﾟンクロータ
  - ﾋﾟﾝクロータ
  - ﾌァッカー
  - ﾌｧッカー
  - ﾌｧｯカー
  - ファックユー
  - ぶっかけ
  - ﾌﾟッシー
  - ﾌﾟｯシー
  - ホスト
  - ホテヘル
  - ポルノ
  - ボンデージ
  - ﾏｴﾂｷ
  - マゾ
  - やくざ
  - ヤクザ
  - 893
  - ラブホ
  - ローション
  - わきが
  - 唖
  - 淫
  - 官能
  - 感染
  - 逆援
  - 巨乳
  - 在日
  - 手淫
  - 消費者金融
  - 生活保護
  - ひきこもり
  - 引き込もり
  - カフェ難民
  - 辱
  - 性交
  - 性病
  - 性癖
  - 精力
  - 多重債務
  - 痴
  - 着エロ
  - 盗撮
  - 覗
  - 破産
  - 爆乳
  - 風俗
  - 変態
  - 変質
  - 便秘
  - 包茎
  - 盲
  - 乱交
  - 露出
  - 聾
  - 咥
  - 猥
  - 腋臭
  - 舐
  - 糞
  - 穢多
  - 非人
  - 売春
  - ロリコン
  - ロリータ
  - 腐女子
  - 片輪
  - 乞食
  - 禿
  - ハゲ
  - きもい
  - キモい
  - キモオタ
  - キモヲタ
  - がいきち
  - ガイキチ
  - 池沼
  - 詐欺
  - 返品
