concurrency: 5
schedule:
  good_morning:
    cron: '0 0 7 * * *'
    class: Makoto::GoodMorningMonologueWorker
  nowplaying:
    cron: '0 0 9,21 * * *'
    class: Makoto::NowplayingMonologueWorker
  good_quote:
    cron: '0 0 5,11,17,23 * * *'
    class: Makoto::GoodQuoteMonologueWorker
  quote_lib:
    every: 5m
    class: Makoto::QuoteLibWorker
  track_lib:
    every: 5m
    class: Makoto::TrackLibWorker
  follow_maintenance:
    every: 5m
    class: Makoto::FollowMaintenanceWorker
