concurrency: 5
schedule:
  good_morning:
    cron: '0 0 7 * * *'
    class: Makoto::GoodMorningMonologueWorker
  nowplaying:
    cron: '0 0 9,21 * * *'
    class: Makoto::NowplayingMonologueWorker
  good_quote:
    cron: '0 0 5,11,17,23 * * *'
    class: Makoto::GoodQuoteMonologueWorker
  precure_birthday:
    cron: '0 1 0 * * *'
    class: Makoto::PrecureBirthdayMonologueWorker
  makoto_birthday:
    cron: '0 10,40 * 4 11 *'
    class: Makoto::MakotoBirthdayMonologueWorker
  quote_lib:
    every: 5m
    class: Makoto::QuoteRefreshWorker
  track_lib:
    every: 5m
    class: Makoto::TrackRefreshWorker
  dictionary:
    every: 5m
    class: Makoto::DictionaryRefreshWorker
  follow_maintenance:
    every: 5m
    class: Makoto::FollowMaintenanceWorker
