filters:
  - name: ci
    cases:
      - analyzer
      - greeting_responder
      - follow_maintenance_worker
      - good_morning_monologue_worker
      - good_quote_monologue_worker
      - makoto_birthday_monologue_worker
      - makoto_birthday_notice_monologue_worker
      - makoto_birthday_live_start_monologue_worker
      - makoto_birthday_live_end_monologue_worker
      - new_year_monologue_worker
      - nowplaying_monologue_worker
      - precure_birthday_monologue_worker
      - cast_birthday_monologue_worker
