name: test
on:
  - push
env:
  CI: "true"
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: makoto
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.0
      - name: apt install
        run: |
          sudo apt update
          sudo apt install postgresql-client
          sudo apt install mecab libmecab-dev mecab-ipadic-utf8
      - name: bundle install
        run: |
          gem install bundler -v '~>2.0'
          bundle install --jobs 4 --retry 3
          bundle exec rake bundle:update
          git diff
          bundle exec rake bundle:check
      - run: bundle exec rake migration:run
      - name: Run lint
        run: |
          bundle exec rubocop
          bundle exec rake erb:lint
